volumes:
  rmq-data:

services:
  rmq:
    image: "rabbitmq:3.7.4-management"
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rmq-data:/var/lib/rabbitmq
      - ./src/test/resources/amqp/definitions.json:/opt/definitions.json
      - ./src/test/resources/amqp/rabbitmq.config:/etc/rabbitmq/rabbitmq.config